In [2]:
# function
def myFunc(param1='default'):
  '''
  ~~~
    document
  '''
  print(param1)
myFunc

<function __main__.myFunc(param1='default')>

In [3]:
myFunc()

default


In [4]:
def square(x):
    return x**2
print(square(3))

9


In [5]:
output = square(5)
print(output)

25


In [6]:
def multBy2(var):return var*2

8

In [8]:
seq2 = [1,2,3]
list(map(multBy2, seq2))

[2, 4, 6]

In [9]:
st = 'Java and C++'
st.lower()

'java and c++'

In [10]:
st.upper()

'JAVA AND C++'

In [11]:
st.split()

['Java', 'and', 'C++']

In [12]:
list = [1,2,3]
list.pop()

3

In [13]:
list

[1, 2]

In [14]:
list.peek()

AttributeError: ignored

In [15]:
'x' in [1,2,3]

False

In [16]:
'x' in ['z', 'y', 'x']

True

In [17]:
# NumPy: it is Linear Algebra library for Python

In [18]:
import numpy as np
# Arrays in np
myList = [1,2,3]
myList

[1, 2, 3]

In [19]:
np.array(myList)

array([1, 2, 3])

In [20]:
myMatrix = [[21,34,53], [1,2,3],[90,0,101]]
myMatrix

[[21, 34, 53], [1, 2, 3], [90, 0, 101]]

In [21]:
np.array(myMatrix)

array([[ 21,  34,  53],
       [  1,   2,   3],
       [ 90,   0, 101]])

In [22]:
np.arrange(0,10)

AttributeError: ignored

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros(5,3)

TypeError: ignored

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.random.rand(2)

array([0.71228142, 0.7966431 ])

In [28]:
np.random.rand(5,3)

array([[0.97725751, 0.77235992, 0.06609663],
       [0.7774981 , 0.8704872 , 0.09624202],
       [0.84152395, 0.74546153, 0.11396733],
       [0.771783  , 0.86312207, 0.91070696],
       [0.29478926, 0.09027157, 0.55958409]])

In [29]:
np.random.randint(1,100)

48

In [30]:
randarray = np.random.randint(0,50,10)

In [31]:
randarray

array([43, 36, 43, 25, 43, 43, 14, 42, 46, 28])

In [32]:
array= np.arange(25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
randarray

array([43, 36, 43, 25, 43, 43, 14, 42, 46, 28])

In [35]:
randarray.max()

46

In [36]:
array.dtype

dtype('int64')

In [37]:
# pandas: glorified excel
import pandas as pd

In [38]:
labels = ['a', 'b', 'c']
myList = [15,23,35]

In [39]:
array = np.array(myList)

In [40]:
dict = {'a':15,'b':23, 'c':35}

In [41]:
array

array([15, 23, 35])

In [42]:
dict

{'a': 15, 'b': 23, 'c': 35}

In [43]:
pd.Series(data=myList)

0    15
1    23
2    35
dtype: int64

In [44]:
pd.Series(data=myList, index = labels)

a    15
b    23
c    35
dtype: int64

In [45]:
pd.Series(myList, labels)

a    15
b    23
c    35
dtype: int64

In [46]:
pd.Series(data=array, index = labels)

a    15
b    23
c    35
dtype: int64

In [53]:
series1 = pd.Series([10.0,20,30,40], index = ['DFW', 'ORD', 'JFK', 'WAS'])

In [48]:
series

NameError: ignored

In [49]:
series1

DFW    10.0
ORD    20.0
JFK    30.0
WAS    40.0
dtype: float64

In [52]:
series2 = pd.Series([10.0,20,30,40], index = ['DFW', 'ORD', 'LGA', 'WAS'])

In [51]:
series2

NameError: ignored

In [54]:
series1 + series2

DFW    20.0
JFK     NaN
LGA     NaN
ORD    40.0
WAS    80.0
dtype: float64

In [55]:
#NaN not a number

In [56]:
series2['DFW']

10.0

In [57]:
series1['DFW']

10.0

In [61]:
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns = 'W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [62]:
df['W','Z']

KeyError: ignored

In [63]:
dfdf[['W', 'Z']]

NameError: ignored

In [64]:
df[['W', 'Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [65]:
type(df['W'])

pandas.core.series.Series

In [66]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [67]:
df['WY'] = df['W'] + df['Y']
df

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [68]:
df.drop('WY',axis = 1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [69]:
df

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [70]:
df1 = df.drop('WY',axis = 1)

In [71]:
df.drop('A', axis=0)

W         X         Y         Z        WY
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [72]:
df.loc['A']

W     2.706850
X     0.628133
Y     0.907969
Z     0.503826
WY    3.614819
Name: A, dtype: float64

In [73]:
df.iloc[2]

W    -2.018168
X     0.740122
Y     0.528813
Z    -0.589001
WY   -1.489355
Name: C, dtype: float64

In [74]:
df.iloc[0]

W     2.706850
X     0.628133
Y     0.907969
Z     0.503826
WY    3.614819
Name: A, dtype: float64

In [75]:
df.loc['B', 'Z']

0.6059653494949336

In [76]:
df

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [77]:
df.loc[['A', 'B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [78]:
df>0

W      X      Y      Z     WY
A   True   True   True   True   True
B   True  False  False   True  False
C  False   True   True  False  False
D   True  False  False   True  False
E   True   True   True   True   True

In [79]:
df[df>0]

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118       NaN       NaN  0.605965       NaN
C       NaN  0.740122  0.528813       NaN       NaN
D  0.188695       NaN       NaN  0.955057       NaN
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [80]:
df[df['w']>0]

KeyError: ignored

In [81]:
df

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [82]:
df[df['W']>0]['Y','X']

KeyError: ignored

In [83]:
df.reset_index()

index         W         X         Y         Z        WY
0     A  2.706850  0.628133  0.907969  0.503826  3.614819
1     B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
2     C -2.018168  0.740122  0.528813 -0.589001 -1.489355
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
4     E  0.190794  1.978757  2.605967  0.683509  2.796762

In [84]:
'CA NY WY OR CO'.split()

['CA', 'NY', 'WY', 'OR', 'CO']

In [85]:
index = 'CA NY WY OR CO'.split()

In [86]:
df['States'] = index

In [87]:
df

W         X         Y         Z        WY States
A  2.706850  0.628133  0.907969  0.503826  3.614819     CA
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959     NY
C -2.018168  0.740122  0.528813 -0.589001 -1.489355     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542     OR
E  0.190794  1.978757  2.605967  0.683509  2.796762     CO

In [88]:
df.set_index('States')

W         X         Y         Z        WY
States                                                  
CA      2.706850  0.628133  0.907969  0.503826  3.614819
NY      0.651118 -0.319318 -0.848077  0.605965 -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001 -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057 -0.744542
CO      0.190794  1.978757  2.605967  0.683509  2.796762

In [89]:
df = df.set_index('States')